---

- hosts: localhost # addresses machine Ansible runs on
  connection: local
  become: true # basically sudo

  tasks:
    - name: Install htop
      apt: 
        name: htop
        state: absent
        autoremove: true
    - name: Install cowsay
      apt:
        name: cowsay
        state: present
    # - name: Install Java and Maven

    # - name: Install Python 3

    # - name: Insta


# Docker
# Java
# Python
# VS Code mit Extensions
# Git
# Repositories dir mit wichtigsten Projekten und Obsidian notes
# Obsidian
# Snap<